### ISSUE TITLE
Fullscreen browser view on mobile devices. (CraftWorlds & More)

### ISSUE THREAD

**Issue by CraftedCube** [xcreatelabs/playir#207]
When saving a game to your homescreen it simply redirects you to the website but in a convenient way... On your homescreen. But, some websites allow it so when you add the website to your homescreen and tap it, the website becomes fullscreen like an app from the AppStore. Here's some pictures.

![image](https://cloud.githubusercontent.com/assets/13810269/14195231/e8c0cbf4-f784-11e5-95fa-e784abaa16b3.png)
![image](https://cloud.githubusercontent.com/assets/13810269/14195232/e9153f54-f784-11e5-97ce-5d45a3d1fe5c.png)
![image](https://cloud.githubusercontent.com/assets/13810269/14195233/e931412c-f784-11e5-9e5f-1edbadf9b26e.png)

As you can see I put this website to my homescreen, am introduced to an app icon, and tap it and find a nice fullscreen application.

I want this not only for my game but I'd be nice for all Playir games and websites, just to give Playir mobile games the more "appy" feel. Plus it looks nicer.

**Comment by CraftedCube** [comment]
Oh and just in case you don't know what I mean by fullscreen, I mean the task bar and search bar stuff at the top has disappeared.

**Comment by CraftedCube** [comment]
@ashcairo

**Comment by ashcairo** [comment]
@CraftedCube should be working now, can you let me know if it works on your device?

**Comment by CraftedCube** [comment]
Fullscreen doesn't seem to be working, I still get the task bar at the top. I can keep trying though.

**Comment by ashcairo** [comment]
@CraftedCube can you try deleting the icon, and re-adding it to the home screen?

**Comment by CraftedCube** [comment]
I re-added it and it's now fullscreen but the icon isn't appearing.

**Comment by CraftedCube** [comment]
The loading screen size is just barely too big also.

![image](https://cloud.githubusercontent.com/assets/13810269/14249301/1e7e1f5c-fa47-11e5-9144-0c47514ed42a.png)

I've also lost my admin privileges.

**Comment by CraftedCube** [comment]
Phone GUI bug is fixed

![image](https://cloud.githubusercontent.com/assets/13810269/14249591/80cd46e6-fa48-11e5-970c-e27dfd662871.jpeg)

**Comment by CraftedCube** [comment]
The GUI needs to be a slight bigger though, text is hard to read and the little icon to get more blocks is super small.

**Comment by CraftedCube** [comment]
Besides the GUI on phones needing to be a bit bigger and me loosing my admin privileges, everything seems to be good

**Comment by CraftedCube** [comment]
@ashcairo I lost my admin privileges, I'm a Guest, I need my account back :tongue:

**Comment by ashcairo** [comment]
Go to playir.com/x/ and make sure you're logged in

**Comment by CraftedCube** [comment]
I'm logged in, and going on safari brings me on my account, but I wanted to use the app icon fullscreen version, and I can't get on the account "CraftedCube"

**Comment by ashcairo** [comment]
@CraftedCube I believe the fullscreen version must be using a different instance to the Safari version. Is there a good location to put in a login button for admin? Perhaps in the info section?

**Comment by CraftedCube** [comment]
Yes the info section would be good.

@ashcairo

**Comment by ashcairo** [comment]
@CraftedCube Added a button to login. Let me know if it works

**Comment by CraftedCube** [comment]
Working and good!

That's it for the bugs, thank you!

I just need a couple of things added in just my game not the template, 2 of them are very simple but for some reason it isn't working for me.

I'm just trying to add music, it plays through every screen in the game. The line of code to do so isn't working for me, so I removed it. Now I'm not amazing at code so it's probably something silly I did.

Anyway this is the track I tried to put in - http://soundimage.org/wp-content/uploads/2015/03/Dancing-on-Clouds.mp3

## It's non-copyrighted but I gave credit in my info section.

I also attempted to make a lava block that takes away 1/4 of a heart away on impact.

I have once face of the block but I couldn't figure out how to make it a voxel

## If you could give directions on how to add blocks to the shop and inventory, that'd be nice.

And this one I didn't even attempt, I needed a scroll bar above the jump button that let's the camera zoom in and out. But not too much where it can go inside the character.

## I need this because when you make a structure you can go inside, you can't see yourself inside the structure so a camera that zoomed in and back out would be helpful.

Also sorry for requesting so many things for the game, I didn't realize how many bugs were in this, I also didn't realize how much I didn't know how to code. Luckily me and my friend are both learning, but at the moment I am a bit limited on how to code.

Thank You.

**Comment by CraftedCube** [comment]
![image](https://cloud.githubusercontent.com/assets/13810269/14300067/fafe9dfc-fb5b-11e5-833a-24621504a06d.jpeg)

**Comment by CraftedCube** [comment]
@ashcairo
