### ISSUE TITLE
CraftWorlds Template - Administration Bug

### ISSUE THREAD

**Issue by CraftedCube** [xcreatelabs/playir#210]
Giving someone Administration permissions doesn't work. Doing so shows you the # but once they leave it goes away.

**Comment by CraftedCube** [comment]
@ashcairo

**Comment by ashcairo** [comment]
@CraftedCube just to confirm, are you saying that if you assign someone as an admin it should be a permanent thing, as in when they re-join they auto get it back?

Until of course you un-admin them?

**Comment by CraftedCube** [comment]
Yep, your exactly correct. 100%

**Comment by CraftedCube** [comment]
Also, notify me when the much simpler visual code editor is released or "pending" because I can't wait for that!

**Comment by CraftedCube** [comment]
Fixed?

**Comment by ashcairo** [comment]
@CraftedCube got it working here, let me know if you have issues with it on your issue

**Comment by ashcairo** [comment]
From @CraftedCube Administration bug is still broken, does it have do do with safari and the fullscreen being 2 different instances?

When I admin someone, sometimes they see their #, but every time they log-off they loose their administration privileges.

**Comment by CraftedCube** [comment]
Let me know when you think you've got it working.

**Comment by CraftedCube** [comment]
@ashcairo I also tested the game on android and it seems to be working good, it's just hard to find a browser that supports WebGL.

**Comment by ashcairo** [comment]
@CraftedCube are you saying that the admin issue is resolved?

**Comment by CraftedCube** [comment]
@ashcairo Hm, I tried to give admin privileges to someone on android and it gave them the # and they left and came back on and it was still there, so then I wrote that on github, but then they left and rejoined again and it was gone. Strange, but the bug is still on-going.

**Comment by ashcairo** [comment]
@CraftedCube is this view from your end or the other persons?

**Comment by ashcairo** [comment]
@CraftedCube Ok, thanks for the info, managed to reproduce this error and just pushed out a fix. Should be available in a few.

**Comment by CraftedCube** [comment]
@ashcairo  Awesome, I'll test it once I get in contact with some people, I still have some enchantments posted on github if you'd like to do that. :smile: 
(No rush :tongue: )
